### PR TITLE
Leaderboard table lifetimeCowsBought and lifetimeCowsSold

### PR DESCRIPTION
**Pull request by RylanPow**
add lifetimeCowsBought and lifetimeCowsSold to the leaderboard table

### CODE REVIEW

**Comment by RylanPow** [comment]
Storybook of the lifetime cows bought and sold added to the leaderboard table:

image

**Review by chriscerie — CHANGES_REQUESTED** [review]
Need before image + storybook link.

**Comment by RylanPow** [comment]
Before:
image

After:
image

Storybook:
https://ucsb-cs156-s23.github.io/proj-happycows-s23-6pm-2/prs/40/storybook/?path=/story/components-leaderboard-leaderboardtable--five-user-commons-admin

**Review by chriscerie — DISMISSED** [review]

**Review by chriscerie — DISMISSED** [review]

**Review by chriscerie — APPROVED** [review]

**Review by pconrad — APPROVED** [review]
LGTM!

**Pull request merged**
